### ISSUE TITLE
Weird behavior with multiple selections

### ISSUE THREAD

**Issue by heston** [jonlabelle/Trimmer#12]
This doesn't seem to work correctly with multiple selections in Sublime 3. It seems to only trim the first selection.

To reproduce:

1. Select a block of multi-line text.
2. Slit selection into lines (Selection > Split into lines)
3. Apply `Trimmer: Trim leading AND trailing whitespace`
4. Observe that strings were not trimmed properly.

**Comment by jonlabelle** [comment]
My guess is because the **Split into Lines** command repositions each cursor to the first line break character of each line in the previous selection (default behavior). If you move the cursor(s) to the start of the line(s) after running the **Split into Lines** command, whitespace trimming should function as intended.
